### PR TITLE
OpenAI example generation and add gpt-5 family support [ #1989 #1990 ] 

### LINKED ISSUE #1989: [bug] AI Copilot bulk example generation
### Describe the bug

When using AI Copilot bulk sample generation on an API contract, the process may stop completely if generation for a single operation/response fails.

This makes the bulk generation workflow unreliable on medium or large contracts, because one malformed AI output can block processing of all remaining items.

### Why this is a bug

Bulk generation is expected to process a set of independent operations/responses. A failure on one item should not block processing of unrelated remaining items.

At the moment, a single invalid AI-generated sample can make the whole bulk workflow unusable, forcing manual restart/rework.

### Expected behavior

Bulk generation should be resilient to per-item failures.

Expected behavior:

1. If one item fails, Microcks should mark it as failed and continue with the next items.
2. Users should be able to resume an interrupted/failed bulk generation without reprocessing already successful items.
3. Users should be able to run generation only for missing examples.
4. Failed items should be optionally retried automatically.
5. On retry, Microcks should be able to include the previous parsing/validation error in the prompt so the model can avoid repeating the same mistake.

### Actual behavior

If one generated sample is invalid (for example malformed YAML/JSON or content that cannot be parsed/validated), the bulk generation flow becomes blocked from the user perspective.

As a result:

- remaining operations/responses are not processed,
- the job cannot be resumed from the last successful item,
- there is no option to skip the failed item and continue,
- there is no built-in retry strategy for failed generations.

### How to Reproduce?

_No response_

### Microcks version or git rev

1.13.2

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

_No response_

### Possible directions for a fix

This issue could be addressed through one or more complementary improvements. These are not necessarily mutually exclusive and could also be combined:

1. **Per-item status tracking**
   Track generation status for each item independently, for example:
   - `pending`
   - `success`
   - `failed`
   - `skipped`

   This would make it possible to avoid treating the whole bulk generation as a single all-or-nothing process.

2. **Continue processing after single-item failure**
   If one item fails validation or parsing, skip it and continue generating the remaining items. 

3. **Resume interrupted generation**
   Allow users to restart a previously interrupted/failed bulk generation job and process only items still marked as `pending` or `failed`, without regenerating successful ones.

4. **Generate only missing examples**
   Add a mode that only targets operations/responses that currently do not already have examples, skipping the ones already populated.

5. **Retry failed items**
   Add a retry mode for failed items only, instead of forcing users to rerun the whole bulk generation.

6. **Retry with previous error context**
   When retrying a failed item, optionally include the previous parsing/validation error in the next prompt, so the model has a chance to correct the specific issue instead of repeating it.

   Example:

   > The previous output failed with this error: `<error message>`.  
   > Please regenerate a valid example and avoid this issue.

7. **Configurable retry behavior**
   Optionally expose controls such as:
   - `maxRetries`
   - retry only on parsing/validation errors
   - `includePreviousErrorInPrompt=true`

Any subset of the above would already improve the reliability of AI Copilot bulk generation, and the best solution may combine several of them.

### LINKED ISSUE #1990: [bug] OpenAI gpt-5 model support
### Describe the bug

When AI Copilot is configured to use GPT-5 family models, the OpenAI request payload appears to include parameters that are not supported for that model/API combination, such as `max_completion_tokens` and/or `logit_bias`.

This causes request failures and prevents AI Copilot from working correctly with GPT-5 models.

### Expected behavior

AI Copilot should build the request payload according to the selected OpenAI API style and model family.

For GPT-5 family models, Microcks should avoid sending unsupported parameters and should use the correct token limit parameter for the target API:

- use only parameters supported by the selected endpoint/model,
- avoid sending `logit_bias` if unsupported,
- avoid sending `max_completion_tokens` if the configured endpoint expects a different field,
- use the proper output token field depending on the API being used.

### Actual behavior

When using a GPT-5 family model in AI Copilot, the generated OpenAI-compatible request may include parameters that are not valid for the selected model or endpoint.

In practice, this results in request errors instead of successful sample generation.

### How to Reproduce?

_No response_

### Microcks version or git rev

1.13.2

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

_No response_

### Additional information

OpenAI documentation differentiates parameter usage depending on the API surface. The Responses API uses `max_output_tokens`, while Chat Completions documents `max_completion_tokens` and also notes compatibility constraints for newer reasoning models.

Because of this, AI Copilot should not assume that legacy/default OpenAI parameters are universally valid for GPT-5 family models.

### PR DESCRIPTION
**Pull request by paulux84**
### Description

  - Refactor OpenAI sample generation to retry when the returned completion cannot be parsed, reusing the previous invalid output and parser error to ask for a corrected example instead of failing immediately.
  - Make AI sample generation more resilient at service level by skipping empty generations and logging per-operation failures without aborting the whole asynchronous run.
  - Add compatibility for GPT-5 family models by using `max_completion_tokens` and conditionally omitting `logit_bias` when the selected model does not support it, while preserving the existing behavior for previous models.

  ### Related issue(s)

  Fixes #1989
  Fixes #1990

### CODE REVIEW

**Comment by lbroudoux** [comment]
Woot! It looks great and I'll try to review this on tomorrow! 
In the meantime, it happens that you have the DCO check failing because your commits are not signed. Can you please check https://github.com/microcks/microcks/pull/1992/checks?check_run_id=67031293428 and fix it so that I'll be able to merge it?
Thanks,

cc @paulux84

**Comment by paulux84** [comment]
I've fixed the problem.

cc @lbroudoux

**Comment by lbroudoux** [comment]
> I've fixed the problem.
> 
> cc @lbroudoux

This is a false positive. I removed the warning. Thanks for pushing the fix, i'll pursue the review asap.

**Comment by paulux84** [comment]
> It looks all good. Thanks for taking the time to put this together @paulux84. I have some work to finalize on `1.13.x` as I'm in the middle of #1901 but will merge it asap.

thanks for your work @lbroudoux ...really useful for dev community

File: webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java [hunk 1]
```diff
@@ -280,4 +255,118 @@ private HttpHeaders createAuthenticationHeaders() {
...
+            return parseCompletionContent(service, operation, content);
+         } catch (Exception e) {
+            retryHistory.add(new RetryTurn(safeErrorMessage(e), content));
+            if (retryIndex == MAX_PARSE_RETRIES) {
+               log.error(
+                     "Could not generate valid AI samples for service {} operation {} after {} retries. Last error: {}",
+                     service.getName(), operation.getName(), MAX_PARSE_RETRIES, safeErrorMessage(e));
+               return new ArrayList<>();
+            }
+            log.warn("Parsing OpenAI output failed for service {} operation {}. Retrying attempt {}/{}. Error: {}",
```
Comment (SebastienDegodez) [inline webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java:282]: Suggestion: Wait a bit before retrying (100-500ms random)
This gives OpenAI time to "cool down", without this, we'd call OpenAI 5 times in a row = bad for the API

```
waitRandom(100, 500) // backoff
```

@lbroudoux ?

File: webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java [hunk 2]
```diff
@@ -280,4 +255,118 @@ private HttpHeaders createAuthenticationHeaders() {
       headers.set("Authorization", "Bearer " + apiKey);
       return headers;
    }
+
+   private List<? extends Exchange> suggestSampleExchangesWithRetry(Service service, Operation operation,
+         String basePrompt) throws Exception {
+      List<RetryTurn> retryHistory = new ArrayList<>();
+
+      for (int retryIndex = 0; retryIndex <= MAX_PARSE_RETRIES; retryIndex++) {
```
Comment (SebastienDegodez) [inline webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java:264]: Suggestion: Replace the FOR loop with a WHILE loop for clarity.


A FOR loop is designed to iterate a KNOWN number of times.
 Here it's misleading because:
 - If the 1st attempt succeeds, we exit immediately via return
 - We don't know in advance how many iterations we'll do
 - The exit condition (if retryIndex == MAX_PARSE_RETRIES) is hidden in the catch block
 
A WHILE is more explicit
- The intent is clear: retry as long as we haven't exceeded the limit
- The counter `attempts++` is at the same place as the check `attempts > MAX`
- Lower bug risk: single source of retry logic (no hidden `retryIndex`)

```
int attempts = 0;
while (attempts <= MAX_PARSE_RETRIES) {
   try {
      return parseCompletionContent(...);
   } catch (Exception e) {
      retryHistory.add(...);
      attempts++;                           // <---- explicite
      
      if (attempts > MAX_PARSE_RETRIES) {   // <---- Check at same line
         return new ArrayList<>();
      }
      waitRandomMS(100, 500);           // <----  
   }
}
```

File: webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java [hunk 3]
```diff
@@ -280,4 +255,118 @@ private HttpHeaders createAuthenticationHeaders() {
...
+            }
+            log.warn("Parsing OpenAI output failed for service {} operation {}. Retrying attempt {}/{}. Error: {}",
+                  service.getName(), operation.getName(), retryIndex + 1, MAX_PARSE_RETRIES, safeErrorMessage(e));
+         }
+      }
+      return new ArrayList<>();
+   }
+
+   private String requestCompletionContent(String prompt) {
+      log.debug("Asking OpenAI to suggest samples for this prompt: {}", prompt);
```
Comment (SebastienDegodez) [inline webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java:290]:
```suggestion
   private String requestCompletionContent(String prompt) {
      if (prompt == null || prompt.trim().isEmpty()) {
         log.warn("Prompt is null or empty");
         return null;
      }
      log.debug("Asking OpenAI to suggest samples for this prompt: {}", prompt);
```

File: webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java [hunk 4]
```diff
@@ -280,4 +255,118 @@ private HttpHeaders createAuthenticationHeaders() {
...
+
+      final List<ChatMessage> messages = new ArrayList<>();
+      final ChatMessage assistantMessage = new ChatMessage(ChatMessageRole.ASSISTANT.value(), prompt);
+      messages.add(assistantMessage);
```
Comment (SebastienDegodez) [inline webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java]:
```suggestion
   final List<ChatMessage> messages = Collections.singletonList(
         new ChatMessage(ChatMessageRole.ASSISTANT.value(), prompt)
   );
```

File: webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java [hunk 5]
```diff
@@ -280,4 +255,118 @@ private HttpHeaders createAuthenticationHeaders() {
...
+         return null;
+      }
+
+      ChatCompletionChoice choice = completionResult.getChoices().get(0);
+      if (choice == null || choice.getMessage() == null) {
+         return null;
+      }
+
+      log.debug("Got this raw output from OpenAI: {}", choice.getMessage().getContent());
+      return choice.getMessage().getContent();
```
Comment (SebastienDegodez) [inline webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java:313]: Extract another method

File: webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java [hunk 6]
```diff
@@ -280,4 +255,118 @@ private HttpHeaders createAuthenticationHeaders() {
...
+
+      final List<ChatMessage> messages = new ArrayList<>();
+      final ChatMessage assistantMessage = new ChatMessage(ChatMessageRole.ASSISTANT.value(), prompt);
+      messages.add(assistantMessage);
+
+      HttpEntity<Map<String, Object>> request = new HttpEntity<>(buildChatCompletionPayload(messages),
+            createAuthenticationHeaders());
+      ResponseEntity<ChatCompletionResult> responseEntity = restTemplate.exchange(apiUrl + "/v1/chat/completions",
+            HttpMethod.POST, request, ChatCompletionResult.class);
+      ChatCompletionResult completionResult = responseEntity.getBody();
```
Comment (SebastienDegodez) [inline webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java:300]: WARNING: 3 possible exception types: HttpClientErrorException (4xx), HttpServerErrorException (5xx) and ResourceAccessException (Connection/Timeout).

File: webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java (hunk 1 above)
Comment (paulux84) [reply webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java:282]: I don’t think a backoff retry is necessary in this case. The error we’re dealing with is not a connection or transient network issue, but rather an invalid or unsatisfactory result returned by the OpenAI model, so a standard backoff strategy doesn’t really apply here.

Note: this mechanism was introduced because, during example generation, the LLM occasionally produces incorrect outputs. Instead of failing immediately the example generation, i've implemented a retry strategy that includes the previous error in the prompt. With this approach, the generation typically succeeds on the second attempt, and at most on the third.

File: webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java (hunk 3 above)
Comment (paulux84) [reply webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java:290]: the prompt can't be null here due to OpenAICopilot::preparePromptForOpenAPI calling

File: webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java (hunk 6 above)
Comment (paulux84) [reply webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java:300]: maybe yes, but all type of exception here and in previous code is correctly catched inside @lbroudoux code

File: webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java (hunk 5 above)
Comment (paulux84) [reply webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java:313]: what do you mean?

File: webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java (hunk 1 above)
Comment (lbroudoux) [reply webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java:282]: Yeah, agree. There's no specific reason to have a backoff retry here, but some wait can be nice to avoid "429 too many requests" style of issue. What do think?

File: webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java (hunk 6 above)
Comment (lbroudoux) [reply webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java:300]: Not sure if it actually makes sense to distinguish the different kinds of exceptions. I think we can handle them as they are now.

File: webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java (hunk 4 above)
Comment (lbroudoux) [reply webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java]: `List.of()` is even more readable than `Collections.singleList()`. I would appreciate the update.

Comment (paulux84) [reply webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java]: I Will try to do that...I'm full of work this week

File: webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java (hunk 2 above)
Comment (lbroudoux) [reply webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java:264]: Agree. `while` loop is more explicit in that case. However, I wouldn't put this on the critical path for the review. It's nice to have if @paulux84 finds some time but we can edit as an after-step otherwise.

Comment (SebastienDegodez) [reply webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java:264]: Of course :)

Comment (lbroudoux) [reply webapp/src/main/java/io/github/microcks/util/ai/OpenAICopilot.java:264]: Let's merge this that way for now so that we'll be able to include it in next 1.14.0-cr2

**Comment by lbroudoux** [comment]
We have a formatting error, but I can fix it just after the merge. I think I'll do it this morning and integrate it into the `1.14.0-rc2` to come.
