### PR TITLE
Remove the OpenAPI version check at importer instantiation time

### LINKED ISSUE #132: OpenAPI Version Check is Too Strict
When the OpenAPI version is quoted, Microcks fails to upload the API, despite displaying a partial success message:
```
openapi: '3.0.0'
info:
  description: 'Super bare bones API'
  version: '1.0.0'
  title: 'Example Microcks API'
```
Results in: 
image
In this case there is no new entry in the API & Services tab, which is unexpected.

Unquoting the version:
```
openapi: 3.0.0
info:
  description: 'Super bare bones API'
  version: '1.0.0'
  title: 'Example Microcks API'
```
Results in:
image
In this case the new service appears in the API & Services tab as expected.

This seems related to #107 but not entirely since in this case the version *is* valid

### PR DESCRIPTION
**Pull request by yahehe**
Resolves #132 

The OpenAPI version is checked before the OpenAPIImporter is instantiated, so it is known to be valid. Additionally, the presence of quotations in the spec causes uploads to report successfully despite the absence of a mocked server. It looks like this is probably due to a file pointer overrun where isYaml remains null, though this has not been verified.

### CODE REVIEW

**Comment by lbroudoux** [comment]
Thanks for the PR. However your changes invalidate #127 and break unit tests.

File: src/main/java/io/github/microcks/util/openapi/OpenAPIImporter.java [hunk 1]
```diff
@@ -71,7 +71,7 @@ public OpenAPIImporter(String specificationFilePath) throws IOException {
                isYaml = false;
                break;
             }
-            else if (line.startsWith("---") || line.startsWith("openapi: 3")) {
+            else if (line.startsWith("---")) {
```
Comment (lbroudoux) [inline src/main/java/io/github/microcks/util/openapi/OpenAPIImporter.java]: Revert #126 that was legit because starting with dashes is not mandatory in YAML

Comment (lbroudoux) [reply src/main/java/io/github/microcks/util/openapi/OpenAPIImporter.java]: Something like `|| line.startsWith("openapi: ")` would not invalidate #126 and make the check less strict. Would you want to update the PR ? Or I'll push something on my side ?

Comment (yahehe) [reply src/main/java/io/github/microcks/util/openapi/OpenAPIImporter.java]: Oooh okay, yeah that makes sense. I can update this today, sorry I didn't notice the failing test

**Comment by lbroudoux** [comment]
Thanks for PR!
