### PR TITLE
chore: fix webapp lint & run lint autofix

### LINKED ISSUE #1165: Lint does not work in webapp
### Reason/Context

As a contributor I want to have automated lint, so I can verify new changes against project rules 

### Description

Fix `ng lint`

### Implementation ideas

_No response_

### PR DESCRIPTION
**Pull request by soGit**
### Description

- Fix lint for webapp
- Run lint autofix

### Related issue(s)

Resolve #1165

### CODE REVIEW

**Comment by soGit** [comment]
Temporary set severity to warning for: 
-     "max-line-length"
-     "no-console"
-     "only-arrow-functions"
-     "triple-equals"
-      "severity"

steel need to fix lint errors for them

**Comment by lbroudoux** [comment]
Wowow... This is a big one! Most of the changes seem to be trivial, but some others can have unexpected side effects....
Have you tried building the application in `prod` mode and running it?

File: webapp/src/main/webapp/src/app/components/day-invocations-bar-chart/day-invocations-bar-chart-component.ts [hunk 1]
```diff
@@ -14,93 +14,131 @@
...
+// import * as d3 from 'd3';
 
 // Thanks to https://github.com/onokumus/metismenu/issues/110#issuecomment-317254128
-//import * as $ from 'jquery';
+// import * as $ from 'jquery';
 declare let $: any;
 
 @Component({
-  selector: 'day-invocations-bar-chart',
+  selector: 'app-day-invocations-bar-chart',
```
Comment (lbroudoux) [inline webapp/src/main/webapp/src/app/components/day-invocations-bar-chart/day-invocations-bar-chart-component.ts:30]: Why this renaming again? As the scope of this component is not the global app, it doesn't make sense to me

File: webapp/src/main/webapp/src/app/components/edit-labels-dialog/edit-labels-dialog.component.html [hunk 2]
```diff
@@ -5,9 +5,9 @@ <h4 class="modal-title pull-left">Edit Labels</h4>
   </button>
 </div>
 <div class="modal-body">
-  <edit-labels [resourceName]="resourceName" [resourceType]="resourceType" [labels]="labels"></edit-labels>
+  <app-edit-labels [resourceName]="resourceName" [resourceType]="resourceType" [labels]="labels"></app-edit-labels>
```
Comment (lbroudoux) [inline webapp/src/main/webapp/src/app/components/edit-labels-dialog/edit-labels-dialog.component.html:8]: OK for renaming here as the scope of this component is global.

File: webapp/src/main/webapp/src/app/components/edit-labels/edit-labels.component.ts [hunk 3]
```diff
@@ -16,46 +16,46 @@
...
 export class EditLabelsComponent implements OnInit {
-  @Output() onSave = new EventEmitter<Map<string, string>>();
+  @Output() save = new EventEmitter<Map<string, string>>();
 
-  @Input('resourceType') resourceType: string;
-  @Input('resourceName') resourceName: string;
-  @Input('labels') labels: any;
+  @Input() resourceType: string;
+  @Input() resourceName: string;
+  @Input() labels: any;
```
Comment (lbroudoux) [inline webapp/src/main/webapp/src/app/components/edit-labels/edit-labels.component.ts:28]: Are you sure that removing the name of Input is safe here? Have you tested it in production mode? (with TS compilation and minification)

File: webapp/src/main/webapp/src/app/components/hour-invocations-bar-chart/hour-invocations-bar-chart.component.ts [hunk 4]
```diff
@@ -33,99 +39,122 @@ const padb = 60;
 const padl = 40;
 
 @Component({
-  selector: 'hour-invocations-bar-chart',
+  selector: 'app-hour-invocations-bar-chart',
```
Comment (lbroudoux) [inline webapp/src/main/webapp/src/app/components/hour-invocations-bar-chart/hour-invocations-bar-chart.component.ts:42]: Not sure the scope of the component is global and so deserves a renaming

File: webapp/src/main/webapp/src/app/components/label-list/label-list.component.ts [hunk 5]
```diff
@@ -18,17 +18,17 @@ import { Component, OnInit, ViewEncapsulation, ChangeDetectionStrategy, Input} f
...
   styleUrls: ['./label-list.component.css'],
   changeDetection: ChangeDetectionStrategy.OnPush
 })
 export class LabelListComponent implements OnInit {
 
-  @Input('metadata') metadata: Metadata
+  @Input() metadata: Metadata;
 
-  @Input('filter') filter: string
+  @Input() filter: string;
```
Comment (lbroudoux) [inline webapp/src/main/webapp/src/app/components/label-list/label-list.component.ts:31]: Is it safe to remove the name of the Input?

File: webapp/src/main/webapp/src/app/components/score-treemap/score-treemap.component.ts [hunk 6]
```diff
@@ -30,25 +30,25 @@ import * as d3 from 'd3';
...
-  @Input('block')
+  @Input()
   block: string;
 
-  @Input('elements')
+  @Input()
   elements: string;
 
-  @Input('legend')
+  @Input()
```
Comment (lbroudoux) [inline webapp/src/main/webapp/src/app/components/score-treemap/score-treemap.component.ts:51]: Is it safe to remove the names of the Inputs?

File: webapp/src/main/webapp/src/app/components/score-treemap/score-treemap.component.ts [hunk 7]
```diff
@@ -177,26 +176,26 @@ export class ScoreTreemapComponent implements OnInit {
...
-    let rgbColor1 = {red: 222, green: 243, blue: 255};    
-    let rgbColor2 = {red: 57, green: 165, blue: 220};
-    let rgbColor3 = {red: 0, green: 67, blue: 104};
-    //background-image: linear-gradient(to left, #def3ff, #39a5dc, #004368);
-    var color1 = rgbColor1;
-    var color2 = rgbColor2;
-    var fade = fadeFraction * 2;
+    const rgbColor1 = {red: 222, green: 243, blue: 255};
+    const rgbColor2 = {red: 57, green: 165, blue: 220};
+    const rgbColor3 = {red: 0, green: 67, blue: 104};
```
Comment (lbroudoux) [inline webapp/src/main/webapp/src/app/components/score-treemap/score-treemap.component.ts:181]: Shouldn't we put these const declarations outside of the function?

File: webapp/src/main/webapp/src/app/models/importer.model.ts [hunk 8]
```diff
@@ -20,13 +20,13 @@ export class ImportJob {
   id: string;
   name: string;
   repositoryUrl: string;
-  mainArtifact: boolean = true;
-  repositoryDisableSSLValidation: boolean = false;
+  mainArtifact = true;
```
Comment (lbroudoux) [inline webapp/src/main/webapp/src/app/models/importer.model.ts:23]: Is removing type a best practice here?

File: webapp/src/main/webapp/src/app/pages/importers/importers.page.ts [hunk 9]
```diff
@@ -102,8 +103,8 @@ export class ImportersPageComponent implements OnInit {
     this.route.queryParams.subscribe(queryParams => {
       // Look at query parameters to apply filters.
       this.filterConfig.appliedFilters = [];
-      if (queryParams['name']) {
-        this.nameFilterTerm = queryParams['name'];
+      if (queryParams.name) {
```
Comment (lbroudoux) [inline webapp/src/main/webapp/src/app/pages/importers/importers.page.ts:106]: Do you think this is actually safe and allow Typescript compilation? `name` is not a declared property on `queryParams` object I think...

File: webapp/src/main/webapp/src/app/pages/importers/service-refs.dialog.ts [hunk 10]
```diff
@@ -0,0 +1,35 @@
+import { Component, OnInit } from '@angular/core';
```
Comment (lbroudoux) [inline webapp/src/main/webapp/src/app/pages/importers/service-refs.dialog.ts:1]: We're missing the LICENSE header here. Could you please add it back?

**Comment by soGit** [comment]
@lbroudoux I did a quick smoke (manual) test. But let me do a code review as well, and I'll check your comments today

File: webapp/src/main/webapp/src/app/components/confirm-delete/confirm-delete.component.ts [hunk 11]
```diff
@@ -13,28 +13,39 @@
...
-import { Component, Output, EventEmitter, ViewChildren, QueryList } from "@angular/core";
+import { Component, Output, EventEmitter, ViewChildren, QueryList } from '@angular/core';
 
-import { ModalDirective } from "ngx-bootstrap/modal";
+import { ModalDirective } from 'ngx-bootstrap/modal';
 
 @Component({
-  selector: "confirm-delete-dialog",
-  templateUrl: "confirm-delete.component.html"
+  selector: 'app-confirm-delete-dialog',
```
[the remark this answers is not in the document]
Comment (soGit) [reply webapp/src/main/webapp/src/app/components/confirm-delete/confirm-delete.component.ts:21]: It's a common practice to prevent name collisions.
Based on angular [style guides "Directive custom prefix"](https://angular.io/guide/styleguide#style-02-08)

By default it's "app-" but we can specify any other. What is your preference? What about using "mrx-"?

File: webapp/src/main/webapp/src/app/components/day-invocations-bar-chart/day-invocations-bar-chart-component.ts (hunk 1 above)
Comment (soGit) [reply webapp/src/main/webapp/src/app/components/day-invocations-bar-chart/day-invocations-bar-chart-component.ts:30]: You can check [angular style guide ](https://angular.io/guide/styleguide#component-custom-prefix) for more details

File: webapp/src/main/webapp/src/app/components/day-invocations-bar-chart/day-invocations-bar-chart-component.ts [hunk 12]
```diff
@@ -14,93 +14,131 @@
...
       bars.append('rect')
-        .attr('width', function() { return x.rangeBand() })
-        .attr('height', function(d) { return height - y(d['total']) })
-        .attr('y', function(d) { return y(d['total']) })
-        .on('click', (d, i) => this.onHourChange.emit(i) )
-        .on('mouseover', function(d) { tooltip.text(d['total'] + " hits"); return tooltip.style("visibility", "visible"); })
-        .on('mousemove', function() { return tooltip.style("top", ((<any>d3.event).pageY - 10) + "px").style("left", ((<any>d3.event).pageX + 10) + "px"); })
-        .on('mouseout', function() { return tooltip.style("visibility", "hidden"); });
+        .attr('width', function() { return x.rangeBand(); })
+        .attr('height', function(d: { key: string; value: any; total: any }) { return height - y(d.total); })
```
[the remark this answers is not in the document]
Comment (soGit) [reply webapp/src/main/webapp/src/app/components/day-invocations-bar-chart/day-invocations-bar-chart-component.ts:136]: Are you talking about dot notation vs bracket notation?

It is common to use dot notation when the property name is known, and use bracket notation when the property name is stored in a variable or the property name has special characters or spaces 

[Read more here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_accessors)

File: webapp/src/main/webapp/src/app/components/edit-labels-dialog/edit-labels-dialog.component.ts [hunk 13]
```diff
@@ -31,19 +31,19 @@ export class EditLabelsDialogComponent implements OnInit {
   labels: any;
   closeBtnName: string;
 
-  labelKV: string = "";
+  labelKV = '';
```
[the remark this answers is not in the document]
Comment (soGit) [reply webapp/src/main/webapp/src/app/components/edit-labels-dialog/edit-labels-dialog.component.ts:34]: It's a no-inferrable-types rule.
_Disallow explicit type declarations for variables or parameters initialized to a number, string, or boolean._

We can customize that, you can read more https://typescript-eslint.io/rules/no-inferrable-types/

File: webapp/src/main/webapp/src/app/components/edit-labels/edit-labels.component.ts (hunk 3 above)
Comment (soGit) [reply webapp/src/main/webapp/src/app/components/edit-labels/edit-labels.component.ts:28]: https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin/docs/rules/no-input-rename.md#-invalid-code-5

File: webapp/src/main/webapp/src/app/components/label-list/label-list.component.ts (hunk 5 above)
Comment (soGit) [reply webapp/src/main/webapp/src/app/components/label-list/label-list.component.ts:31]: Yes, it's a general approach to avid specifying name in a decorator

File: webapp/src/main/webapp/src/app/components/score-treemap/score-treemap.component.ts (hunk 7 above)
Comment (soGit) [reply webapp/src/main/webapp/src/app/components/score-treemap/score-treemap.component.ts:181]: We can, it's a good idea to store reusable constants outside of component. Do you want me to make changes in this pull request or as a separate one?

File: webapp/src/main/webapp/src/app/pages/importers/importers.page.ts (hunk 9 above)
Comment (soGit) [reply webapp/src/main/webapp/src/app/pages/importers/importers.page.ts:106]: No difference in that case

File: webapp/src/main/webapp/src/app/pages/importers/service-refs.dialog.ts (hunk 10 above)
Comment (soGit) [reply webapp/src/main/webapp/src/app/pages/importers/service-refs.dialog.ts:16]: updated

File: webapp/src/main/webapp/src/app/components/confirm-delete/confirm-delete.component.ts (hunk 11 above)
[the remark this answers is not in the document]
Comment (lbroudoux) [reply webapp/src/main/webapp/src/app/components/confirm-delete/confirm-delete.component.ts:21]: That's great! I was not aware of this convention.

File: webapp/src/main/webapp/src/app/components/edit-labels-dialog/edit-labels-dialog.component.ts (hunk 13 above)
[the remark this answers is not in the document]
Comment (lbroudoux) [reply webapp/src/main/webapp/src/app/components/edit-labels-dialog/edit-labels-dialog.component.ts:34]: Thanks for explanation.

File: webapp/src/main/webapp/src/app/components/edit-labels/edit-labels.component.ts (hunk 3 above)
Comment (lbroudoux) [reply webapp/src/main/webapp/src/app/components/edit-labels/edit-labels.component.ts:28]: Thanks for references.
